# Generated by Django 4.1.7 on 2023-02-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0005_alter_teacher_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
