# Generated by Django 4.1.7 on 2023-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0006_remove_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='ansor.group'),
        ),
    ]
