# Generated by Django 4.1.7 on 2023-02-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0008_remove_teacher_group_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
