# Generated by Django 4.1.7 on 2023-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0009_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
