# Generated by Django 4.1.7 on 2023-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0010_group_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.FloatField(default=600000, max_length=1000000),
        ),
    ]
