# Generated by Django 4.1.7 on 2023-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
