# Generated by Django 4.1.7 on 2023-02-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansor', '0013_group_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='students',
            new_name='attended_students',
        ),
    ]
